/**
 * Content_Hierarchy Entity
 * Stores the structure of the study material
 * Hebrew: היררכיית תוכן
 */

export const Content_Hierarchy = {
  name: 'Content_Hierarchy',
  displayName: 'היררכיית תוכן',
  fields: {
    id: {
      type: 'id',
      required: true,
      primaryKey: true
    },
    category_name: {
      type: 'text',
      required: true,
      displayName: 'שם קטגוריה',
      description: 'למשל: "חירום רפואי"'
    },
    topic_name: {
      type: 'text',
      required: true,
      displayName: 'שם נושא',
      description: 'למשל: "החייאה"'
    },
    lesson_source: {
      type: 'text',
      required: false,
      displayName: 'מקור השיעור',
      description: 'למשל: "Transcript_2024_Scan"'
    },
    createdAt: {
      type: 'datetime',
      autoGenerated: true
    },
    updatedAt: {
      type: 'datetime',
      autoGenerated: true
    }
  },
  indexes: [
    { fields: ['category_name'] },
    { fields: ['topic_name'] },
    { fields: ['category_name', 'topic_name'] }
  ],
  permissions: {
    read: ['authenticated'],
    create: ['admin', 'instructor'],
    update: ['admin', 'instructor'],
    delete: ['admin']
  }
};
