/**
 * Question_Bank Entity
 * The core repository of all questions
 * Hebrew: בנק שאלות
 */

import {
  QUESTION_CATEGORIES,
  THINKING_LEVELS,
  TRAINING_LEVELS,
  QUESTION_STATUSES,
  QUESTION_TYPES_UI,
} from '../shared/questionBankMetadata.js';

export const Question_Bank = {
  name: 'Question_Bank',
  displayName: 'בנק שאלות',
  fields: {
    id: {
      type: 'id',
      required: true,
      primaryKey: true,
    },
    category: {
      type: 'select',
      required: true,
      displayName: 'פרק (קטגוריה)',
      description: 'מספר פרק ושם',
      options: QUESTION_CATEGORIES,
    },
    sub_category: {
      type: 'select',
      required: true,
      displayName: 'תת־קטגוריה',
      description: 'תת־פרק (רשימת placeholder לעת עתה)',
      options: [],
    },
    thinking_level: {
      type: 'select',
      required: true,
      displayName: 'רמת חשיבה',
      options: THINKING_LEVELS,
    },
    training_level: {
      type: 'select',
      required: true,
      displayName: 'רמת הכשרה',
      description: 'A=ALS, B=BLS, C=CLS, D=DLS, E=ELS',
      options: TRAINING_LEVELS,
    },
    has_media: {
      type: 'boolean',
      required: true,
      displayName: 'יש מדיה',
      readOnly: true,
      defaultValue: false,
      description: 'מחושב אוטומטית לפי צרוף סטטי או תג מאגר מדיה',
    },
    question_type: {
      type: 'select',
      required: true,
      displayName: 'סוג שאלה',
      options: QUESTION_TYPES_UI,
      defaultValue: 'single_choice',
    },
    question_text: {
      type: 'richtext',
      required: true,
      displayName: 'טקסט השאלה',
      description: 'תוכן השאלה בפורמט עשיר',
    },
    media_attachment: {
      type: 'file',
      required: false,
      displayName: 'מדיה מצורפת',
      description: 'תמונה / וידאו / אודיו / PDF (לא בשילוב עם תג מאגר)',
      accept: 'image/*,video/*,audio/*,application/pdf',
    },
    media_bank_tag: {
      type: 'text',
      required: false,
      displayName: 'תג מאגר מדיה',
      description: 'תג לבחירת מדיה אקראית מהמאגר (לא יחד עם קובץ סטטי)',
    },
    correct_answer: {
      type: 'text',
      required: false,
      displayName: 'תשובה נכונה',
      description: 'JSON או טקסט להערכה אוטומטית',
    },
    explanation: {
      type: 'richtext',
      required: false,
      displayName: 'הסבר',
      description: 'הסבר למה התשובה נכונה - מוצג אחרי תשובה שגויה',
    },
    hint: {
      type: 'text',
      required: false,
      displayName: 'רמז',
      description: 'טיפ לפני תשובה (אופציונלי)',
    },
    status: {
      type: 'select',
      required: true,
      displayName: 'סטטוס',
      options: QUESTION_STATUSES,
      defaultValue: 'draft',
    },
    total_attempts: {
      type: 'number',
      required: true,
      displayName: 'סה"כ ניסיונות',
      defaultValue: 0,
      readOnly: true,
    },
    total_success: {
      type: 'number',
      required: true,
      displayName: 'סה"כ הצלחות',
      defaultValue: 0,
      readOnly: true,
    },
    success_rate: {
      type: 'number',
      required: true,
      displayName: 'אחוז הצלחה',
      defaultValue: 0,
      readOnly: true,
      description: 'מחושב אוטומטית: (total_success / total_attempts) * 100',
    },
    createdAt: {
      type: 'datetime',
      autoGenerated: true,
    },
    updatedAt: {
      type: 'datetime',
      autoGenerated: true,
    },
  },
  indexes: [
    { fields: ['category'] },
    { fields: ['sub_category'] },
    { fields: ['thinking_level'] },
    { fields: ['training_level'] },
    { fields: ['question_type'] },
    { fields: ['status'] },
    { fields: ['has_media'] },
    { fields: ['media_bank_tag'] },
    { fields: ['status', 'question_type'] },
  ],
  permissions: {
    read: ['authenticated'],
    create: ['admin', 'instructor'],
    update: ['admin', 'instructor'],
    delete: ['admin'],
  },
};
