/**
 * Study_Plans Entity
 * Learning plans created by instructors
 * Hebrew: תוכניות לימוד
 */

export const Study_Plans = {
  name: 'Study_Plans',
  displayName: 'תוכניות לימוד',
  fields: {
    plan_id: {
      type: 'id',
      required: true,
      primaryKey: true
    },
    instructor_id: {
      type: 'reference',
      referenceTo: 'Users',
      required: true,
      displayName: 'מדריך',
      description: 'המדריך שיצר את התוכנית'
    },
    title: {
      type: 'text',
      required: true,
      displayName: 'כותרת',
      description: 'שם התוכנית'
    },
    description: {
      type: 'text',
      required: false,
      displayName: 'תיאור',
      description: 'תיאור התוכנית'
    },
    categories: {
      type: 'array',
      required: false,
      displayName: 'קטגוריות',
      description: 'רשימת קטגוריות בתוכנית',
      items: {
        type: 'text'
      },
      defaultValue: []
    },
    topics: {
      type: 'array',
      required: false,
      displayName: 'נושאים',
      description: 'רשימת נושאים בתוכנית',
      items: {
        type: 'text'
      },
      defaultValue: []
    },
    order: {
      type: 'array',
      required: false,
      displayName: 'סדר לימוד',
      description: 'סדר מומלץ לנושאים (JSON)',
      items: {
        type: 'text'
      },
      defaultValue: []
    },
    daily_goal: {
      type: 'number',
      required: true,
      displayName: 'יעד יומי',
      description: 'מספר שאלות מומלץ ליום',
      min: 1,
      defaultValue: 10
    },
    is_active: {
      type: 'boolean',
      required: true,
      displayName: 'פעיל',
      description: 'האם התוכנית פעילה',
      defaultValue: true
    },
    created_at: {
      type: 'datetime',
      required: true,
      displayName: 'תאריך יצירה',
      defaultValue: 'now'
    },
    updated_at: {
      type: 'datetime',
      autoGenerated: true
    }
  },
  indexes: [
    { fields: ['instructor_id'] },
    { fields: ['is_active'] },
    { fields: ['created_at'] }
  ],
  permissions: {
    read: ['authenticated'],
    create: ['instructor', 'admin'],
    update: ['instructor', 'admin'],
    delete: ['admin']
  }
};
