/**
 * Users Entity
 * Simple user management
 * Hebrew: משתמשים
 */

export const Users = {
  name: 'Users',
  displayName: 'משתמשים',
  fields: {
    user_id: {
      type: 'text',
      required: true,
      primaryKey: true,
      displayName: 'תעודת זהות מד"א',
      description: 'מספר זיהוי אישי של מד"א'
    },
    full_name: {
      type: 'text',
      required: true,
      displayName: 'שם מלא'
    },
    email: {
      type: 'email',
      required: false,
      displayName: 'אימייל',
      description: 'כתובת אימייל (נדרש להתחברות עם Google)'
    },
    role: {
      type: 'select',
      required: true,
      displayName: 'תפקיד',
      options: [
        { value: 'trainee', label: 'מתאמן' },
        { value: 'instructor', label: 'מדריך' },
        { value: 'admin', label: 'מנהל' }
      ],
      defaultValue: 'trainee'
    },
    auth_provider: {
      type: 'select',
      required: false,
      displayName: 'ספק אימות',
      options: [
        { value: 'local', label: 'מקומי' },
        { value: 'google', label: 'Google' }
      ],
      defaultValue: 'local'
    },
    google_id: {
      type: 'text',
      required: false,
      displayName: 'מזהה Google',
      description: 'מזהה ייחודי מ-Google OAuth'
    },
    profile_picture: {
      type: 'text',
      required: false,
      displayName: 'תמונת פרופיל',
      description: 'URL לתמונת פרופיל'
    },
    email_verified: {
      type: 'boolean',
      required: false,
      displayName: 'אימייל מאומת',
      defaultValue: false
    },
    points: {
      type: 'number',
      required: true,
      displayName: 'נקודות',
      description: 'נקודות שנצברו במערכת',
      defaultValue: 0,
      min: 0
    },
    current_streak: {
      type: 'number',
      required: true,
      displayName: 'רצף נוכחי',
      description: 'מספר ימים רצופים עם פעילות',
      defaultValue: 0,
      min: 0
    },
    longest_streak: {
      type: 'number',
      required: true,
      displayName: 'רצף ארוך ביותר',
      description: 'מספר הימים הרצופים הגבוה ביותר',
      defaultValue: 0,
      min: 0
    },
    createdAt: {
      type: 'datetime',
      autoGenerated: true
    },
    updatedAt: {
      type: 'datetime',
      autoGenerated: true
    }
  },
  indexes: [
    { fields: ['user_id'] },
    { fields: ['email'] },
    { fields: ['google_id'] },
    { fields: ['role'] },
    { fields: ['points'] },
    { fields: ['current_streak'] }
  ],
  permissions: {
    read: ['authenticated'],
    create: ['admin'],
    update: ['admin'],
    delete: ['admin']
  }
};
