/**
 * User_Notes Entity
 * User notes and bookmarks for questions
 * Hebrew: הערות משתמש
 */

export const User_Notes = {
  name: 'User_Notes',
  displayName: 'הערות משתמש',
  fields: {
    note_id: {
      type: 'id',
      required: true,
      primaryKey: true
    },
    user_id: {
      type: 'reference',
      referenceTo: 'Users',
      required: true,
      displayName: 'משתמש'
    },
    question_id: {
      type: 'reference',
      referenceTo: 'Question_Bank',
      required: true,
      displayName: 'שאלה'
    },
    note_text: {
      type: 'text',
      required: false,
      displayName: 'הערה',
      description: 'הערה אישית על השאלה'
    },
    is_bookmark: {
      type: 'boolean',
      required: true,
      displayName: 'סימניה',
      description: 'האם זו סימניה',
      defaultValue: false
    },
    created_at: {
      type: 'datetime',
      required: true,
      displayName: 'תאריך יצירה',
      defaultValue: 'now'
    },
    updated_at: {
      type: 'datetime',
      autoGenerated: true
    }
  },
  indexes: [
    { fields: ['user_id'] },
    { fields: ['question_id'] },
    { fields: ['user_id', 'question_id'] },
    { fields: ['is_bookmark'] },
    { fields: ['user_id', 'is_bookmark'] }
  ],
  permissions: {
    read: ['authenticated'],
    create: ['authenticated'],
    update: ['authenticated'],
    delete: ['authenticated', 'admin']
  }
};
